### ISSUE TITLE
Tailing with recursion

### ISSUE THREAD

**Issue by yeungda** [suzuken/kinesis-tail#1]
Thanks for publishing this! I'm new to Kinesis and this has come in handy.

I noticed that there is [infinite recursion](https://github.com/suzuken/kinesis-tail/blob/master/main.go#L71) in the tool. I believe each recursion will result in the call stack growing. This memory leak will grow slowly presumably, since the recursion happens every 3 seconds, but nevertheless, I wonder what will happen if you left it tailing for a while?

[This article](http://dave.cheney.net/2013/06/02/why-is-a-goroutines-stack-infinite) about infinite recursion in go seems to explain the problem.

**Comment by suzuken** [comment]
Sorry for late reply. Thank you for your comment.

Yes, this tool using infinite recursion. It's useful for debug purpose. kinesis-tail wait for new records until put in.

> This article about infinite recursion in go seems to explain the problem.

Thanks. It may cause problem when long running purpose. I'll look into this.

**Comment by suzuken** [comment]
In #2, I fix above by using `for` loop for iterating Kinesis Stream. Thank you for reporting!
